// Sample jobs for local development when MongoDB is not connected

export const SAMPLE_JOBS = [
  {
    _id: '1',
    title: 'SSC CGL 2025 - Combined Graduate Level Examination',
    slug: 'ssc-cgl-2025',
    organization: 'Staff Selection Commission',
    department: 'Department of Personnel & Training',
    category: 'Central Govt',
    subCategory: 'SSC',
    totalVacancies: 17727,
    eligibility: {
      age: { min: 18, max: 32 },
      ageRelaxation: 'OBC: 3 years, SC/ST: 5 years, PwD: 10 years',
      education: "Bachelor's Degree from a recognized University",
      experience: 'Not required',
    },
    importantDates: {
      notificationDate: '2025-06-01',
      applicationStart: '2025-06-15',
      applicationEnd: '2025-07-15',
      examDate: '2025-09-01',
      admitCardDate: '2025-08-15',
      resultDate: '2025-11-01',
    },
    applicationFee: { general: 100, obc: 100, scSt: 0, female: 0, exServiceman: 0 },
    salary: { payScale: 'Level 4 to Level 8', minSalary: 25500, maxSalary: 151100, inHandEstimate: 32000 },
    location: 'All India',
    applyOnlineLink: 'https://ssc.gov.in',
    officialNotificationLink: 'https://ssc.gov.in/noticeboards',
    officialWebsite: 'https://ssc.gov.in',
    examPattern: 'Tier 1: CBT (100 questions, 200 marks, 60 min)\nTier 2: CBT (Paper I, II, III)',
    selectionProcess: 'Tier 1 CBT → Tier 2 CBT → Document Verification → Final Selection',
    statesAccepted: ['All India'],
    isActive: true,
    isFeatured: true,
    views: 45230,
    createdAt: '2025-06-01T00:00:00.000Z',
    updatedAt: '2025-06-01T00:00:00.000Z',
  },
  {
    _id: '2',
    title: 'IBPS PO 2025 - Probationary Officer Recruitment',
    slug: 'ibps-po-2025',
    organization: 'Institute of Banking Personnel Selection',
    department: 'Banking',
    category: 'Banking',
    subCategory: 'IBPS',
    totalVacancies: 4455,
    eligibility: {
      age: { min: 20, max: 30 },
      ageRelaxation: 'OBC: 3 years, SC/ST: 5 years',
      education: "Bachelor's Degree in any discipline",
      experience: 'Not required',
    },
    importantDates: {
      notificationDate: '2025-06-20',
      applicationStart: '2025-07-01',
      applicationEnd: '2025-08-01',
      examDate: '2025-10-15',
      admitCardDate: '2025-10-01',
      resultDate: '2025-12-15',
    },
    applicationFee: { general: 850, obc: 850, scSt: 175, female: 175, exServiceman: 175 },
    salary: { payScale: 'JMGS-I', minSalary: 36000, maxSalary: 63840, inHandEstimate: 52000 },
    location: 'All India',
    applyOnlineLink: 'https://ibps.in',
    officialNotificationLink: 'https://ibps.in',
    officialWebsite: 'https://ibps.in',
    examPattern: 'Prelims: 100 questions (60 min) → Mains: 200 questions (180 min)',
    selectionProcess: 'Prelims → Mains → Interview → Final Selection',
    statesAccepted: ['All India'],
    isActive: true,
    isFeatured: true,
    views: 32100,
    createdAt: '2025-06-20T00:00:00.000Z',
    updatedAt: '2025-06-20T00:00:00.000Z',
  },
  {
    _id: '3',
    title: 'RRB NTPC 2025 - Non Technical Popular Categories',
    slug: 'rrb-ntpc-2025',
    organization: 'Railway Recruitment Board',
    department: 'Indian Railways',
    category: 'Central Govt',
    subCategory: 'Railway',
    totalVacancies: 35281,
    eligibility: {
      age: { min: 18, max: 33 },
      ageRelaxation: 'OBC: 3 years, SC/ST: 5 years',
      education: '12th Pass / Graduate (varies by post)',
      experience: 'Not required',
    },
    importantDates: {
      notificationDate: '2025-05-15',
      applicationStart: '2025-06-01',
      applicationEnd: '2025-06-30',
      examDate: '2025-08-20',
      admitCardDate: '2025-08-05',
      resultDate: '2025-10-30',
    },
    applicationFee: { general: 500, obc: 500, scSt: 250, female: 250, exServiceman: 250 },
    salary: { payScale: 'Level 2 to Level 6', minSalary: 19900, maxSalary: 112400, inHandEstimate: 28000 },
    location: 'All India',
    applyOnlineLink: 'https://indianrailways.gov.in',
    officialNotificationLink: 'https://indianrailways.gov.in',
    officialWebsite: 'https://indianrailways.gov.in',
    examPattern: 'CBT-1: 100 questions (90 min) → CBT-2: 120 questions (90 min)',
    selectionProcess: 'CBT-1 → CBT-2 → Typing Test/CBAT → Document Verification',
    statesAccepted: ['All India'],
    isActive: true,
    isFeatured: true,
    views: 67800,
    createdAt: '2025-05-15T00:00:00.000Z',
    updatedAt: '2025-05-15T00:00:00.000Z',
  },
  {
    _id: '4',
    title: 'UPSC Civil Services (IAS/IPS) 2025',
    slug: 'upsc-cse-2025',
    organization: 'Union Public Service Commission',
    department: 'Central Government',
    category: 'Central Govt',
    subCategory: 'UPSC',
    totalVacancies: 1056,
    eligibility: {
      age: { min: 21, max: 32 },
      ageRelaxation: 'OBC: 3 years, SC/ST: 5 years',
      education: "Bachelor's Degree from a recognized University",
      experience: 'Not required',
    },
    importantDates: {
      notificationDate: '2025-02-01',
      applicationStart: '2025-02-15',
      applicationEnd: '2025-06-20',
      examDate: '2025-07-01',
      admitCardDate: '2025-06-15',
      resultDate: '2025-08-30',
    },
    applicationFee: { general: 100, obc: 100, scSt: 0, female: 0, exServiceman: 0 },
    salary: { payScale: 'Level 10 to Level 17', minSalary: 56100, maxSalary: 225000, inHandEstimate: 80000 },
    location: 'All India',
    applyOnlineLink: 'https://upsc.gov.in',
    officialNotificationLink: 'https://upsc.gov.in',
    officialWebsite: 'https://upsc.gov.in',
    examPattern: 'Prelims (GS + CSAT) → Mains (9 papers) → Interview',
    selectionProcess: 'Prelims → Mains → Interview → Final Merit List',
    statesAccepted: ['All India'],
    isActive: true,
    isFeatured: true,
    views: 89500,
    createdAt: '2025-02-01T00:00:00.000Z',
    updatedAt: '2025-02-01T00:00:00.000Z',
  },
  {
    _id: '5',
    title: 'Indian Army Agniveer Rally 2025',
    slug: 'indian-army-agniveer-2025',
    organization: 'Indian Army',
    department: 'Ministry of Defence',
    category: 'Defence',
    subCategory: 'Indian Army',
    totalVacancies: 46000,
    eligibility: {
      age: { min: 17, max: 21 },
      ageRelaxation: 'As per Army rules',
      education: '10th / 12th Pass (varies by trade)',
      experience: 'Not required',
    },
    importantDates: {
      notificationDate: '2025-05-01',
      applicationStart: '2025-05-15',
      applicationEnd: '2025-07-10',
      examDate: '2025-08-01',
      admitCardDate: '2025-07-20',
      resultDate: '2025-09-15',
    },
    applicationFee: { general: 0, obc: 0, scSt: 0, female: 0, exServiceman: 0 },
    salary: { payScale: 'Agniveer Package', minSalary: 30000, maxSalary: 40000, inHandEstimate: 30000 },
    location: 'All India',
    applyOnlineLink: 'https://joinindianarmy.nic.in',
    officialNotificationLink: 'https://joinindianarmy.nic.in',
    officialWebsite: 'https://joinindianarmy.nic.in',
    examPattern: 'Written Test + Physical Fitness Test + Medical',
    selectionProcess: 'Online Registration → Rally → Written Test → Medical → Merit List',
    statesAccepted: ['All India'],
    isActive: true,
    isFeatured: true,
    views: 125000,
    createdAt: '2025-05-01T00:00:00.000Z',
    updatedAt: '2025-05-01T00:00:00.000Z',
  },
  {
    _id: '6',
    title: 'KVS Teacher Recruitment 2025',
    slug: 'kvs-teacher-2025',
    organization: 'Kendriya Vidyalaya Sangathan',
    department: 'Ministry of Education',
    category: 'Teaching',
    subCategory: 'KVS',
    totalVacancies: 13404,
    eligibility: {
      age: { min: 18, max: 40 },
      ageRelaxation: 'OBC: 3 years, SC/ST: 5 years',
      education: "B.Ed with Bachelor's/Master's Degree",
      experience: 'As per KVS norms',
    },
    importantDates: {
      notificationDate: '2025-07-01',
      applicationStart: '2025-07-15',
      applicationEnd: '2025-08-15',
      examDate: '2025-10-20',
      admitCardDate: '2025-10-05',
      resultDate: '2025-12-30',
    },
    applicationFee: { general: 1500, obc: 1500, scSt: 0, female: 0, exServiceman: 0 },
    salary: { payScale: 'Level 6 to Level 12', minSalary: 35400, maxSalary: 209200, inHandEstimate: 45000 },
    location: 'All India',
    applyOnlineLink: 'https://kvsangathan.nic.in',
    officialNotificationLink: 'https://kvsangathan.nic.in',
    officialWebsite: 'https://kvsangathan.nic.in',
    examPattern: 'Written Test (150 questions, 150 marks, 150 min)',
    selectionProcess: 'Written Test → Interview → Document Verification → Final Selection',
    statesAccepted: ['All India'],
    isActive: true,
    isFeatured: false,
    views: 34200,
    createdAt: '2025-07-01T00:00:00.000Z',
    updatedAt: '2025-07-01T00:00:00.000Z',
  },
  {
    _id: '7',
    title: 'SBI Clerk 2025 - Junior Associate Recruitment',
    slug: 'sbi-clerk-2025',
    organization: 'State Bank of India',
    department: 'Banking',
    category: 'Banking',
    subCategory: 'SBI',
    totalVacancies: 13735,
    eligibility: {
      age: { min: 20, max: 28 },
      ageRelaxation: 'OBC: 3 years, SC/ST: 5 years',
      education: "Bachelor's Degree in any discipline",
      experience: 'Not required',
    },
    importantDates: {
      notificationDate: '2025-06-10',
      applicationStart: '2025-06-25',
      applicationEnd: '2025-07-25',
      examDate: '2025-09-20',
      admitCardDate: '2025-09-05',
      resultDate: '2025-11-15',
    },
    applicationFee: { general: 750, obc: 750, scSt: 0, female: 0, exServiceman: 0 },
    salary: { payScale: 'Clerical Grade', minSalary: 22000, maxSalary: 45000, inHandEstimate: 28000 },
    location: 'All India',
    applyOnlineLink: 'https://sbi.co.in/careers',
    officialNotificationLink: 'https://sbi.co.in/careers',
    officialWebsite: 'https://sbi.co.in',
    examPattern: 'Prelims: 100 questions (60 min) → Mains: 190 questions (160 min)',
    selectionProcess: 'Prelims → Mains → Local Language Test → Final Selection',
    statesAccepted: ['All India'],
    isActive: true,
    isFeatured: false,
    views: 54300,
    createdAt: '2025-06-10T00:00:00.000Z',
    updatedAt: '2025-06-10T00:00:00.000Z',
  },
  {
    _id: '8',
    title: 'TSPSC Group 1 Services 2025',
    slug: 'tspsc-group-1-2025',
    organization: 'Telangana State PSC',
    department: 'Telangana State Government',
    category: 'State Govt',
    subCategory: 'TSPSC',
    totalVacancies: 563,
    eligibility: {
      age: { min: 18, max: 44 },
      ageRelaxation: 'As per TS Government rules',
      education: "Bachelor's Degree from a recognized University",
      experience: 'Not required',
    },
    importantDates: {
      notificationDate: '2025-05-20',
      applicationStart: '2025-06-05',
      applicationEnd: '2025-07-05',
      examDate: '2025-09-10',
      admitCardDate: '2025-08-25',
      resultDate: '2025-12-01',
    },
    applicationFee: { general: 800, obc: 800, scSt: 400, female: 400, exServiceman: 400 },
    salary: { payScale: 'Level 13 to Level 16', minSalary: 56100, maxSalary: 205400, inHandEstimate: 75000 },
    location: 'Telangana',
    applyOnlineLink: 'https://tspsc.gov.in',
    officialNotificationLink: 'https://tspsc.gov.in',
    officialWebsite: 'https://tspsc.gov.in',
    examPattern: 'Prelims (150 questions) → Mains (6 papers) → Interview',
    selectionProcess: 'Prelims → Mains → Interview → Document Verification',
    statesAccepted: ['Telangana'],
    isActive: true,
    isFeatured: false,
    views: 21500,
    createdAt: '2025-05-20T00:00:00.000Z',
    updatedAt: '2025-05-20T00:00:00.000Z',
  },
  {
    _id: '9',
    title: 'SSC CHSL 2025 - Combined Higher Secondary Level',
    slug: 'ssc-chsl-2025',
    organization: 'Staff Selection Commission',
    department: 'Department of Personnel & Training',
    category: 'Central Govt',
    subCategory: 'SSC',
    totalVacancies: 6000,
    eligibility: {
      age: { min: 18, max: 27 },
      ageRelaxation: 'OBC: 3 years, SC/ST: 5 years',
      education: '12th Pass from a recognized Board',
      experience: 'Not required',
    },
    importantDates: {
      notificationDate: '2025-07-10',
      applicationStart: '2025-07-20',
      applicationEnd: '2025-08-20',
      examDate: '2025-11-01',
      admitCardDate: '2025-10-15',
      resultDate: '2026-01-15',
    },
    applicationFee: { general: 100, obc: 100, scSt: 0, female: 0, exServiceman: 0 },
    salary: { payScale: 'Level 2 to Level 4', minSalary: 19900, maxSalary: 81100, inHandEstimate: 25000 },
    location: 'All India',
    applyOnlineLink: 'https://ssc.gov.in',
    officialNotificationLink: 'https://ssc.gov.in',
    officialWebsite: 'https://ssc.gov.in',
    examPattern: 'Tier 1: CBT (100 questions, 200 marks, 60 min) → Tier 2: Typing/Skill Test',
    selectionProcess: 'Tier 1 CBT → Tier 2 Skill Test → Document Verification',
    statesAccepted: ['All India'],
    isActive: true,
    isFeatured: false,
    views: 38700,
    createdAt: '2025-07-10T00:00:00.000Z',
    updatedAt: '2025-07-10T00:00:00.000Z',
  },
  {
    _id: '10',
    title: 'NDA 2 Examination 2025',
    slug: 'nda-2-2025',
    organization: 'Union Public Service Commission',
    department: 'Ministry of Defence',
    category: 'Defence',
    subCategory: 'NDA',
    totalVacancies: 400,
    eligibility: {
      age: { min: 16, max: 19 },
      ageRelaxation: 'None',
      education: '12th Pass / Appearing (Science stream for Navy/AF)',
      experience: 'Not required',
    },
    importantDates: {
      notificationDate: '2025-06-01',
      applicationStart: '2025-06-15',
      applicationEnd: '2025-07-10',
      examDate: '2025-08-15',
      admitCardDate: '2025-08-01',
      resultDate: '2025-10-15',
    },
    applicationFee: { general: 100, obc: 100, scSt: 0, female: 0, exServiceman: 0 },
    salary: { payScale: 'Lieutenant Level', minSalary: 56100, maxSalary: 177500, inHandEstimate: 70000 },
    location: 'All India',
    applyOnlineLink: 'https://upsc.gov.in',
    officialNotificationLink: 'https://upsc.gov.in',
    officialWebsite: 'https://upsc.gov.in',
    examPattern: 'Written (Math 300 + GAT 600 marks) → SSB Interview (900 marks)',
    selectionProcess: 'Written Exam → SSB Interview → Medical → Merit List',
    statesAccepted: ['All India'],
    isActive: true,
    isFeatured: false,
    views: 78900,
    createdAt: '2025-06-01T00:00:00.000Z',
    updatedAt: '2025-06-01T00:00:00.000Z',
  },
];
